name: 'Set project version'
description: 'Set project version to YYYY.MM.DD.BUILD'

inputs:
  version-file:
    description: 'File containing project version'
    required: false
    default: package.json
  version-stub:
    description: 'Version hardcoded in project file and replaced with resulting one'
    required: false
    default: '0.0.0'
  leading-zeros:
    description: 'Pad month and day with 0: 06 vs 6'
    required: false
    default: true
  time-zone:
    description: Time zone to be used to determine the current date/time
    required: false

outputs:
  project-version:
    description: "Project version"
    value: ${{ steps.set-version.outputs.project-version }}

runs:
  using: "composite"
  steps:
    - name: Set project version to current date in YYYY.MM.DD.BUILD format
      id: set-version
      run: |
        [[ ${{ inputs.time-zone != '' }} ]] && export TZ=${{ inputs.time-zone }}
        VERSION=$(date $([[ ${{ inputs.leading-zeros }} = true ]] && echo '+%Y.%m.%d' || echo '+%Y.%-m.%-d')).${{ github.run_number }}
        echo "Set project version to '$VERSION'"
        sed -i "s/${{ inputs.version-stub }}/$VERSION/" ${{ inputs.version-file }}
        echo "project-version=$VERSION" >> $GITHUB_OUTPUT
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "::group::Modified ${{ inputs.version-file }}"
        cat ${{ inputs.version-file }}
        echo "::endgroup::"
      shell: bash
