name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Australia/Sydney
    steps:
    - uses: actions/checkout@v2
    - name: Set project version for .NET project
      id: set-version
      uses: EduardSergeev/project-version-action@v1
      with:
        version-file: test/dotnet/example/example.csproj
        version-stub: '0.0.0.0'      
    - name: Test if version '${{ steps.set-version.outputs.project-version }}' is correctly set for .NET project
      run: dotnet test test/dotnet/example -- TestRunParameters.Parameter\(name=\"version\",\ value=\"${{ steps.set-version.outputs.project-version }}\"\)
