name: build

on:
  push:

env:
  TZ: Australia/Sydney

jobs:
  node-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set project version for Node project
      uses: './'
      with:
        version-file: test/node/example/package.json    
    - name: Test if version '${{ env.VERSION }}' is correctly set for Node project
      run: cd test/node/example && npm install && npm test

  dotnet-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set project version for .NET project
      uses: './'
      with:
        version-file: test/dotnet/example/example.csproj
        version-stub: '0.0.0.0'      
    - name: Test if version '${{ env.VERSION }}' is correctly set for .NET project
      run: dotnet test test/dotnet/example -- TestRunParameters.Parameter\(name=\"version\",\ value=\"${{ env.VERSION }}\"\)

  cabal-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set project version for Cabal project
      uses: './'
      with:
        version-file: test/cabal/example/example.cabal
        leading-zeros: false    
    - name: Test if version '${{ env.VERSION }}' is correctly set for Cabal project
      run: cd test/cabal/example && cabal build

  cabal-leading-zeros-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set current date to '2021.06.07'
      run: sudo date -s 2021-06-07
    - name: Set project version for Cabal project
      uses: './'
      with:
        version-file: test/cabal/example/example.cabal    
        leading-zeros: false    
    - name: Test if version '${{ env.VERSION }}' is correctly set for Cabal project
      run: cd test/cabal/example && cabal build
